# [user@hostname:directory] git:(branch) *
# directory trimming: %(5~|%-1~/…/%3~|%4~)
#

export EDITOR=vim;

ZSH_COLORIZE_CHROMA_FORMATTER=terminal256
ZSH_COLORIZE_STYLE="solarized-dark"

PS1='[%{$fg[green]%}%n%{$reset_color%}@%{$fg[magenta]%}%m%{$reset_color%}:%{$fg[cyan]%}%(5~|%-1~/.../%3~|%4~)%{$reset_color%}] $(git_prompt_info)%{$reset_color%}$ '

unsetopt inc_append_history
